import type { Metadata } from "next";
// import { Playfair_Display } from "next/font/google";
import { Saira } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";

const saira = Saira({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-saira", // optional: for CSS variable usage
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en flex flex-col min-h-screen">
      <body className={`${saira.variable} antialiased`}>
        <main  className="flex-grow">{children}</main>

      </body>
    </html>
  );
}
